// One selected model per biological structure.
export const DEFAULT_DISPLAY_SCALE = 5 / 6; // Match the heart for future organs.
export const organs = [
  {
    id: 'pancreas', name: { zh: '胰腺', en: 'Pancreas' },
    description: { zh: '胰腺位于上腹部胃的后方，横向延伸至脾门附近，兼具消化和内分泌功能。通常可按胰头、胰颈、胰体和胰尾理解，并与十二指肠及胆道区域相邻。本模型用于观察胰腺自身整体外形。', en: 'The pancreas lies behind the stomach and extends toward the splenic hilum. It has digestive and endocrine roles and is commonly described as head, neck, body, and tail, adjacent to the duodenum and biliary region. This model is for observing the organ’s own overall form.' },
    observationPoints: { zh: ['旋转模型，观察胰腺横向延伸及头、体、尾的大致连续外形。', '从正面、后方或侧方比较胰腺自身的轮廓、长轴和表面转折。'], en: ['Rotate the model to inspect the broad transverse form and the approximate continuity of head, body, and tail.', 'Use frontal, posterior, or lateral views to compare the organ’s contour, long axis, and surface turns.'] },
    modelId: 'meshy-pancreas-texture-0924102023',
    parts: ['./models/meshy-pancreas-texture-0924102023/meshopt-halftex-v1-3657f06c50bf.glb'],
    bytes: 7629648,
    downloadParts: ['./models/meshy-pancreas-texture-0924102023/model.glb'],
    downloadBytes: 14520404,
    downloadUrl: './models/meshy-pancreas-texture-0924102023/model.glb',
  },
  {
    id: 'spleen', name: { zh: '脾脏', en: 'Spleen' },
    description: { zh: '脾脏位于左上腹、胃的左后方，邻近膈肌、左肾和胰尾。它通常呈椭圆或楔形，外侧面较隆凸，内侧面可见与血管和邻近器官相关的区域。本模型适合观察整体轮廓、长轴和不同表面的形态变化。', en: 'The spleen lies in the left upper abdomen, posterolateral to the stomach and near the diaphragm, left kidney, and pancreatic tail. It is generally oval or wedge-shaped, with a convex outer surface and a medial hilar region. This model supports observation of the overall contour, long axis, and differences between its surfaces.' },
    observationPoints: { zh: ['旋转至外侧面，观察脾脏的长轴、隆凸轮廓和上下端。', '切换后方或内侧视角，比较脾脏自身的表面转折、凹面和脾门侧轮廓。'], en: ['Rotate to the lateral surface to inspect the long axis, convex contour, and superior and inferior ends.', 'Switch to posterior or medial views to compare the organ’s surface turns, concavity, and hilar-side contour.'] },
    modelId: 'meshy-spleen-texture-0924102034',
    parts: ['./models/meshy-spleen-texture-0924102034/meshopt-halftex-v1-8eb0b3362991.glb'],
    bytes: 2495384,
    downloadParts: ['./models/meshy-spleen-texture-0924102034/model.glb'],
    downloadBytes: 7566312,
    downloadUrl: './models/meshy-spleen-texture-0924102034/model.glb',
  },
  {
    id: 'teeth', name: { zh: '牙与牙列', en: 'Teeth and dentition' },
    description: { zh: '牙列由上下颌牙齿按弓形排列组成，可按切牙、尖牙、前磨牙和磨牙观察其位置与形态差异。牙冠、牙根和咬合面是外观辨认的基本线索。本模型用于观察牙列排列、牙弓形态和咬合方向。', en: 'The dentition consists of teeth arranged in upper and lower arches. Incisors, canines, premolars, and molars differ in position and form. Crowns, roots, and occlusal surfaces provide basic visual landmarks. This model is for observing arch arrangement and occlusal orientation.' },
    observationPoints: { zh: ['从正面观察上下牙列的弓形排列、前牙位置和左右对称趋势。', '从咬合面或侧面查看牙冠形态、牙弓深度和上下列的接触方向。'], en: ['Use a frontal view to inspect the arch arrangement, anterior teeth, and approximate left-right symmetry.', 'Use occlusal or lateral views to examine crown forms, arch depth, and the direction of upper-lower contact.'] },
    modelId: 'meshy-teeth-texture-0924102050',
    parts: ['./models/meshy-teeth-texture-0924102050/meshopt-halftex-v1-e671c55024e8.glb'],
    bytes: 14648052,
    downloadParts: ['./models/meshy-teeth-texture-0924102050/model.glb'],
    downloadBytes: 24953488,
    downloadUrl: './models/meshy-teeth-texture-0924102050/model.glb',
  },
  {
    id: 'heart', name: { zh: '心脏', en: 'Heart' },
    description: { zh: '心脏位于纵隔内，整体呈锥形，心尖偏向左前下方，基底朝向后上方。外观可按前面、膈面、底部和房室沟等区域理解，并结合大血管根部判断方向。本模型主要用于观察外部轮廓和方向。', en: 'The heart lies in the mediastinum and has a broadly conical form, with the apex directed leftward, anteriorly, and inferiorly, and the base directed posteriorly and superiorly. Its surfaces, grooves, and great-vessel roots help establish orientation. This model focuses on external form and direction.' },
    observationPoints: { zh: ['旋转到前方，辨认心尖、前面轮廓以及大血管根部的大致方向。', '从后方或下方观察心底、膈面和房室沟的外部走向。'], en: ['Rotate to the anterior view to identify the apex, anterior contour, and approximate direction of the great-vessel roots.', 'Use posterior or inferior views to inspect the base, diaphragmatic surface, and external atrioventricular groove.'] },
    displayScale: DEFAULT_DISPLAY_SCALE,
    modelId: 'user-heart-20260928', assetProfile: 'original',
    parts: ['./models/user-heart-20260928/model.glb'], bytes: 9803592,
    downloadParts: ['./models/user-heart-20260928/model.glb'], downloadBytes: 9803592,
    downloadUrl: './models/user-heart-20260928/model.glb',
  },
  {
    id: 'brain', name: { zh: '脑', en: 'Brain' },
    description: { zh: '脑由左右大脑半球、小脑和脑干等主要部分组成，表面可见脑沟和脑回形成的复杂纹理。大脑纵裂、外侧面轮廓和后下方的小脑有助于建立方向。本模型用于观察整体形态与表面分区，不代表完整内部结构。', en: 'The brain includes the cerebral hemispheres, cerebellum, and brainstem. Its surface shows the complex pattern of gyri and sulci. The longitudinal fissure, lateral contours, and posteroinferior cerebellum help establish orientation. This model is for overall form and surface regions, not complete internal anatomy.' },
    observationPoints: { zh: ['从上方或侧方观察大脑半球的外轮廓、纵裂和主要表面起伏。', '转向后下方，查看小脑与脑干所在区域的相对位置和连续外形。'], en: ['Use superior or lateral views to inspect the cerebral contours, longitudinal fissure, and major surface relief.', 'Turn to a posteroinferior view to examine the relative position and external continuity of the cerebellar and brainstem regions.'] },
    displayScale: DEFAULT_DISPLAY_SCALE,
    modelId: 'user-brain-20260928', assetProfile: 'original',
    parts: ['./models/user-brain-20260928/model.glb'], bytes: 50487636,
    downloadParts: ['./models/user-brain-20260928/model.glb'], downloadBytes: 50487636,
    downloadUrl: './models/user-brain-20260928/model.glb',
  },
  {
    id: 'kidneys', name: { zh: '肾脏与输尿管', en: 'Kidneys and ureters' },
    description: { zh: '肾脏位于腹膜后间隙，左右各一，通常右肾位置略低。肾脏外形近似豆形，内侧缘有肾门，输尿管由肾门区域向下延伸至骨盆。本模型适合观察双侧肾脏的相对位置和输尿管的外部走行。', en: 'The paired kidneys lie in the retroperitoneum, with the right commonly positioned slightly lower. Each kidney is bean-shaped with a medial hilum, and the ureter descends from the hilar region toward the pelvis. This model supports observation of bilateral position and external ureteral course.' },
    observationPoints: { zh: ['从前方或后方比较左右肾脏的高度、长轴和内侧肾门方向。', '沿输尿管向下旋转观察其从肾门区域离开并向骨盆方向延伸的外形。'], en: ['Use anterior or posterior views to compare kidney height, long axes, and medial hilar directions.', 'Follow the ureters downward to inspect their external continuation from the hilar regions toward the pelvis.'] },
    displayScale: 1,
    displayOffsetY: 0.16,
    modelId: 'user-kidneys-20260928', assetProfile: 'original',
    parts: ['./models/user-kidneys-20260928/model.glb'], bytes: 6194000,
    downloadParts: ['./models/user-kidneys-20260928/model.glb'], downloadBytes: 6194000,
    downloadUrl: './models/user-kidneys-20260928/model.glb',
  },
  {
    id: 'liver', name: { zh: '肝脏', en: 'Liver' },
    description: { zh: '肝脏位于右上腹、膈肌下方，体积较大，外形可分为膈面和脏面。右叶通常较大，脏面可见与胆囊窝、血管和邻近器官相关的区域。本模型用于观察整体轮廓、上下方向和主要表面差异。', en: 'The liver occupies the right upper abdomen beneath the diaphragm and has a large overall volume. Its diaphragmatic and visceral surfaces provide useful orientation; the right lobe is usually larger, with visceral landmarks related to the gallbladder and vessels. This model focuses on external form and orientation.' },
    observationPoints: { zh: ['从前上方观察肝脏的膈面、右叶优势和整体弧形轮廓。', '转到下方或后下方，查看脏面凹凸变化及胆囊窝所在的大致区域。'], en: ['Use an anterosuperior view to inspect the diaphragmatic surface, right-lobe dominance, and broad curved contour.', 'Turn inferiorly or posteroinferiorly to examine visceral-surface relief and the approximate gallbladder-bed region.'] },
    modelId: 'user-liver-20260928', assetProfile: 'original',
    parts: ['./models/user-liver-20260928/model.glb'], bytes: 5067976,
    downloadParts: ['./models/user-liver-20260928/model.glb'], downloadBytes: 5067976,
    downloadUrl: './models/user-liver-20260928/model.glb',
  },
  {
    id: 'stomach', name: { zh: '胃', en: 'Stomach' },
    description: { zh: '胃位于上腹部，连接食管与十二指肠，外形常呈弯曲的囊状结构。大弯、小弯、胃底、胃体和幽门方向是观察胃外形的常用线索。本模型适合比较胃的长轴、弯曲轮廓和两端区域的外形变化。', en: 'The stomach lies in the upper abdomen between the esophagus and duodenum and has a curved sac-like form. The greater and lesser curvatures, fundus, body, and pyloric direction provide useful landmarks. This model supports observation of the long axis, curved contour, and changes in form toward either end.' },
    observationPoints: { zh: ['从前方观察胃底、胃体和大弯形成的主要外轮廓。', '从右侧或下方查看胃自身的幽门方向、弯曲轮廓和整体长轴。'], en: ['Use an anterior view to inspect the fundus, body, and the main contour formed by the greater curvature.', 'Use right-lateral or inferior views to examine the stomach’s pyloric direction, curved contour, and overall long axis.'] },
    modelId: 'meshy-stomach-texture-0920145532',
    parts: ['./models/meshy-stomach-texture-0920145532/meshopt-lod-v1-fd6070f0482b.glb'],
    bytes: 587652,
    downloadParts: ['./models/meshy-stomach-texture-0920145532/model.glb'],
    downloadBytes: 7479168,
    downloadUrl: './models/meshy-stomach-texture-0920145532/model.glb',
  },
  {
    id: 'lungs', name: { zh: '肺与支气管', en: 'Lungs and bronchi' },
    description: { zh: '肺位于胸腔两侧，左右形态并不完全相同；肺尖向上，肺底贴近膈肌，内侧面有肺门区域。气管向下分为左右主支气管并继续分支。本模型用于观察肺的外形、肺门方向和可见气道走行，不等同于完整末梢结构。', en: 'The lungs occupy the two sides of the thorax and are not identical in form. Each apex points upward, the base rests on the diaphragm, and the medial surface contains the hilar region. The trachea divides into main bronchi and branches further. This model shows external form, hilar direction, and visible airway course, not every distal structure.' },
    observationPoints: { zh: ['从前方比较左右肺的外轮廓、肺尖、肺底和纵隔侧边界。', '从内侧或后方沿气管向下，观察主支气管及模型中可见的分支走向。'], en: ['Use an anterior view to compare the contours, apices, bases, and mediastinal borders of the lungs.', 'From medial or posterior views, follow the trachea downward to inspect the main bronchi and visible branch directions.'] },
    modelId: 'user-lungs-20260928', assetProfile: 'original',
    parts: ['./models/user-lungs-20260928/model.glb'], bytes: 16487720,
    downloadParts: ['./models/user-lungs-20260928/model.glb'], downloadBytes: 16487720,
    downloadUrl: './models/user-lungs-20260928/model.glb',
  },
  {
    id: 'alveoli', name: { zh: '肺泡', en: 'Alveoli' },
    description: { zh: '肺泡是肺内气体交换的微小结构，通常成簇分布于呼吸道末端。其薄壁与周围毛细血管共同构成气体交换界面。本模型是局部结构的放大展示，可用于观察囊状轮廓和空间排列；颜色和比例为展示表达，不能据此判断真实组织尺寸或完整微观层次。', en: 'Alveoli are small gas-exchange structures clustered at the ends of respiratory passages. Their thin walls and surrounding capillaries form the gas-exchange interface. This enlarged local model supports observation of sac-like forms and spatial arrangement; display colors and proportions do not establish tissue dimensions or complete microscopic layers.' },
    observationPoints: { zh: ['旋转观察囊状单元的聚集方式与可见通道。', '比较不同方向的表面形态，遮挡区域需旋转后观察。'], en: ['Rotate to inspect the grouping of sac-like units and visible passages.', 'Compare surface forms from different directions and rotate to reveal obscured regions.'] },
    modelId: 'user-alveoli-20260928', assetProfile: 'original',
    parts: ['./models/user-alveoli-20260928/model.glb'], bytes: 8299132,
    downloadParts: ['./models/user-alveoli-20260928/model.glb'], downloadBytes: 8299132,
    downloadUrl: './models/user-alveoli-20260928/model.glb',
  },
  {
    id: 'thorax', name: { zh: '胸部心肺', en: 'Thoracic organs' },
    description: { zh: '胸部的肺与心脏在空间上紧密相邻：左右肺分布于两侧，心脏位于两肺之间的纵隔区域，气管向下延续为支气管。本模型组合展示心脏、双肺及相关气道和血管，可用于比较整体位置关系；没有包含完整骨性胸廓，内部细节可能被外层表面遮挡。', en: 'The lungs and heart are closely related within the thorax. The lungs lie on either side of the mediastinum, which contains the heart, while the trachea continues into the bronchi. This assembly contains the heart, both lungs, and associated airways and vessels for spatial comparison. It does not include the complete bony thorax, and outer surfaces may obscure internal details.' },
    observationPoints: { zh: ['从前方和侧方比较胸部轮廓、左右分布与纵向层次。', '旋转至后方，观察可见结构之间的连接和遮挡关系。'], en: ['Compare the thoracic outline, bilateral arrangement, and vertical levels from front and side views.', 'Rotate posteriorly to examine visible connections and occlusion between structures.'] },
    modelId: 'user-thorax-20260928', assetProfile: 'original',
    parts: ['./models/user-thorax-20260928/model.glb'], bytes: 25900496,
    downloadParts: ['./models/user-thorax-20260928/model.glb'], downloadBytes: 25900496,
    downloadUrl: './models/user-thorax-20260928/model.glb',
  },
  {
    id: 'ribosome', name: { zh: '核糖体', en: 'Ribosome' },
    description: { zh: '核糖体是细胞内参与蛋白质合成的结构，由核糖体 RNA 和蛋白质组成，通常分为大、小两个亚基。它根据信使 RNA 携带的信息参与多肽链的合成。本模型用于观察核糖体的整体形态和可见分区；不同颜色仅辅助区分形态，不等同于逐分子身份或真实原子尺度。', en: 'Ribosomes synthesize proteins using information carried by messenger RNA. They contain ribosomal RNA and proteins and comprise large and small subunits. This model supports observation of overall form and visible regions. Colors assist visual distinction and do not establish individual molecular identities or atomic scale.' },
    observationPoints: { zh: ['旋转观察整体轮廓以及较大、较小区域的相对位置。', '比较不同表面的凹凸与间隙，不以颜色直接推断分子身份。'], en: ['Rotate to inspect the overall outline and relative positions of larger and smaller regions.', 'Compare surface relief and gaps without inferring molecular identity from color alone.'] },
    modelId: 'user-ribosome-20260928', assetProfile: 'original',
    parts: ['./models/user-ribosome-20260928/model.glb'], bytes: 11030176,
    downloadParts: ['./models/user-ribosome-20260928/model.glb'], downloadBytes: 11030176,
    downloadUrl: './models/user-ribosome-20260928/model.glb',
  },
  {
    id: 'chloroplast', name: { zh: '叶绿体', en: 'Chloroplast' },
    description: { zh: '叶绿体是植物及部分藻类细胞中进行光合作用的细胞器，内部具有类囊体膜系统和基质，类囊体可堆叠形成基粒。本模型初始显示完整外形，可用切片和旋转检查不同方向的截面；内部结构可能仍被多层表面遮挡。颜色用于辅助展示，不代表真实尺寸比例。', en: 'Chloroplasts carry out photosynthesis in plants and some algae. They contain stroma and a thylakoid membrane system, with thylakoids often stacked into grana. This model initially shows the outer form. Use section controls and rotation to inspect cross-sections; multiple surfaces may still obscure internal structures. Display colors do not establish true dimensional proportions.' },
    observationPoints: { zh: ['旋转观察整体外轮廓、长轴和表面弧度。', '开启切片并调整方向与深度，比较实际可见的截面。'], en: ['Rotate to inspect the overall outline, long axis, and surface curvature.', 'Enable sections and adjust the axis and depth to compare the cross-sections actually visible.'] },
    modelId: 'user-chloroplast-20260928', assetProfile: 'original',
    parts: ['./models/user-chloroplast-20260928/model.glb'], bytes: 3489104,
    downloadParts: ['./models/user-chloroplast-20260928/model.glb'], downloadBytes: 3489104,
    downloadUrl: './models/user-chloroplast-20260928/model.glb',
  },
];

export const messages = {
  zh: {
    download: '下载高清模型',
    home: '首页', about: '关于',
    tour: '模型漫游', pauseTour: '暂停漫游', playTour: '播放漫游', nextOrgan: '下一个器官', openModel: '查看模型',
    skip: '跳到内容', overview: '总览', organs: '器官', collection: '人体解剖', plantCollection: '植物解剖', taskGeneralization: '任务泛化', taskSidebar: '任务泛化侧边栏', modelDirectory: '目录', openCollection: '展开人体解剖', closeCollection: '收起人体解剖', featured: '精选器官',
    model: '3D 模型', reset: '复位视角', expand: '放大展示', collapse: '收起展示',
    front: '正面', back: '背面', left: '左侧', right: '右侧', zoomIn: '放大', zoomOut: '缩小',
    hint: '左键旋转 · 右键平移 · 滚轮缩放', previewHint: '拖动旋转 · 放大后可使用完整操作', canvas: '可交互三维模型：方向键旋转，加减键缩放，0 复位', previewCanvas: '三维模型预览：拖动或使用方向键旋转，放大后可使用完整操作',
    rotate: '自动旋转', pause: '停止旋转', explode: '组件拆分', explodeDegree: '拆分程度', explodeUnavailable: '此模型没有可独立拆分的组件', slice: '切片', axis: '切片轴', depth: '位置', flip: '反向',
    sliceNote: '切片显示现有模型截面；视角与切片轴按模型坐标定义。',
    retry: '重新加载',
    loading: '正在加载模型', preparing: '正在准备三维视图…', error: '模型未能加载，请重试。',
    noWebGL: '三维视图暂不可用，请检查浏览器的图形加速设置后重试。',
    dark: '切换深色', light: '切换浅色', viewLabel: '模型坐标视角',
    progress: '模型加载进度', navigation: '主导航', observationTitle: '观察要点', anatomyNote: '解剖介绍供对照阅读，模型细节以实际展示为准。',
  },
  en: {
    download: 'Download HD model',
    home: 'Home', about: 'About',
    tour: 'Model tour', pauseTour: 'Pause tour', playTour: 'Play tour', nextOrgan: 'Next organ', openModel: 'Explore model',
    skip: 'Skip to content', overview: 'Overview', organs: 'Organs', collection: 'Human Anatomy', plantCollection: 'Plant Anatomy', taskGeneralization: 'Task Generalization', taskSidebar: 'Task generalization sidebar', modelDirectory: 'Directory', openCollection: 'Open human anatomy', closeCollection: 'Close human anatomy', featured: 'Featured organ',
    model: '3D model', reset: 'Reset view', expand: 'Expand viewer', collapse: 'Collapse viewer',
    front: 'Front', back: 'Back', left: 'Left', right: 'Right', zoomIn: 'Zoom in', zoomOut: 'Zoom out',
    hint: 'Left drag to rotate · Right drag to pan · Scroll to zoom', previewHint: 'Drag to rotate · Expand for full controls', canvas: 'Interactive 3D model: arrow keys to rotate, plus and minus to zoom, 0 to reset', previewCanvas: '3D model preview: drag or use arrow keys to rotate; expand for full controls',
    rotate: 'Auto-rotate', pause: 'Stop rotation', explode: 'Separate components', explodeDegree: 'Separation', explodeUnavailable: 'This model has no independently separable components', slice: 'Section', axis: 'Axis', depth: 'Position', flip: 'Flip',
    sliceNote: 'Sections reveal the existing mesh. Views and section axes use model coordinates.',
    retry: 'Try again',
    loading: 'Loading model', preparing: 'Preparing 3D view…', error: 'The model could not be loaded. Please try again.',
    noWebGL: '3D view is unavailable. Check browser graphics acceleration and try again.',
    dark: 'Switch to dark mode', light: 'Switch to light mode', viewLabel: 'Model-coordinate views',
    progress: 'Model loading progress', navigation: 'Main navigation', observationTitle: 'Observation points', anatomyNote: 'The anatomy note is for reference; model details follow the actual display.',
  },
};
